# NOTE: update this with your service name
service: ppp-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  profileTableName: ${self:custom.stage}-profile
  messageTableName: ${self:custom.stage}-message
  chatTableName: ${self:custom.stage}-chat
  appTableName: ${self:custom.stage}-app
  userPoolName: ${self:custom.stage}-ppp-api
  userPoolClientName: ${self:custom.stage}-ppp-api
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  # Load our webpack config
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  # Load our secret environment variables based on the current stage.
  # Fallback to default if it is not in prod.
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  apiKeys:
    - ${self:custom.stage}-ppp-trada
  usagePlan:
    quota:
      limit: 1000
      period: DAY
    throttle:
      burstLimit: 200
      rateLimit: 100

  environment:
    profileTableName: ${self:custom.profileTableName}
    messageTableName: ${self:custom.messageTableName}
    chatTableName: ${self:custom.chatTableName}
    appTableName: ${self:custom.appTableName}
    twilioAccountSid: ${self:custom.environment.twilioAccountSid}
    twilioAuthToken: ${self:custom.environment.twilioAuthToken}
    msgPrefix: ${self:custom.environment.msgPrefix}
    sendGridKey: ${self:custom.environment.sendGridKey}
    userPoolName: ${self:custom.userPoolName}
    userPoolClientName: ${self:custom.userPoolClientName}
    historyEndpoint: ${self:custom.environment.historyEndpoint}
    authUtilContract: ${self:custom.environment.authUtilContract}
    authRetries: ${self:custom.environment.authRetries}
    startAuthTimeout: ${self:custom.environment.startAuthTimeout}
    minAuthTimeout: ${self:custom.environment.minAuthTimeout}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:TransactWrite
        - dynamodb:TransactGet
      Resource:
        - "Fn::GetAtt": [ ProfileTable, Arn ]
        - "Fn::GetAtt": [ MessageTable, Arn ]
        - "Fn::GetAtt": [ ChatTable, Arn ]
        - "Fn::GetAtt": [ AppTable, Arn ]
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: 
        - { "Fn::Join": [ "/", [ 
            { "Fn::GetAtt": ["ProfileTable", "Arn" ] }, "index", "*" 
          ]]}
        - { "Fn::Join": [ "/", [ 
            { "Fn::GetAtt": ["MessageTable", "Arn" ] }, "index", "*" 
          ]]}
        - { "Fn::Join": [ "/", [ 
            { "Fn::GetAtt": ["ChatTable", "Arn" ] }, "index", "*" 
          ]]}
        - { "Fn::Join": [ "/", [ 
            { "Fn::GetAtt": ["AppTable", "Arn" ] }, "index", "*" 
          ]]}
    - Effect: Allow
      Action:
        - secretsmanager:Describe*
        - secretsmanager:Get*
        - secretsmanager:List
      Resource: "*"
    - Effect: Allow
      Action:
        - cognito-idp:ListUsers
      Resource: "*"
    

functions:
  register:
    handler: register.main
    events:
      - http:
          path: register
          method: post
          authorizer: aws_iam
          cors: true

  send-msg:
    handler: send-msg.main
    events:
      - http:
          path: send-msg
          method: post
          authorizer: aws_iam
          cors: true

  send-msg-prv:
    handler: send-msg.main
    events:
      - http:
          path: send-msg-prv
          method: post
          private: true
          cors: true
    
  get-profiles:
    handler: get-profiles.main
    events:
      - http:
          path: get-profiles
          method: post
          authorizer: aws_iam
          cors: true

  get-messages:
    handler: get-messages.main
    events:
      - http:
          path: get-messages
          method: post
          authorizer: aws_iam
          cors: true  

  verify-sms:
    handler: verify-otp.sms
    events:
      - http:
          path: verify-sms
          method: post
          authorizer: aws_iam
          cors: true  

  verify-email:
    handler: verify-otp.email
    events:
      - http:
          path: verify-email
          method: post
          authorizer: aws_iam
          cors: true
          
  get-profile:
    handler: get-profile.main
    events:
      - http:
          path: get-profile
          method: post
          authorizer: aws_iam
          cors: true
  get-chats:
    handler: get-chats.main
    events:
      - http:
          path: get-chats
          method: post
          authorizer: aws_iam
          cors: true
  search-profiles:
    handler: search-profiles.main
    events:
      - http:
          path: search-profiles
          method: post
          authorizer: aws_iam
          cors: true
  pre-sign-up:
    handler: pre-sign-up.main
    events:
      - cognitoUserPool:
          pool: CommProfileServicePool1
          trigger: PreSignUp
  create-auth-challenge:
    handler: create-auth-challenge.main
    events:
      - cognitoUserPool:
          pool: CommProfileServicePool1
          trigger: CreateAuthChallenge
  verify-auth-challenge:
    handler: verify-auth-challenge.main
    events:
      - cognitoUserPool:
          pool: CommProfileServicePool1
          trigger: VerifyAuthChallengeResponse
  define-auth-challenge:
    handler: define-auth-challenge.main
    events:
      - cognitoUserPool:
          pool: CommProfileServicePool1
          trigger: DefineAuthChallenge
          
resources:
  # Congnito User Pool
  - ${file(resources/cognito-user-pool.yml)}
  # Congnito Identity Pool
  - ${file(resources/cognito-identity-pool.yml)}
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/profile-table.yml)}
  - ${file(resources/message-table.yml)}
  - ${file(resources/app-table.yml)}
  - ${file(resources/chat-table.yml)}
  # S3 Bucket
  - ${file(resources/s3-bucket.yml)}