Resources:
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.appTableName}
      AttributeDefinitions:
        - AttributeName: appId
          AttributeType: S
        - AttributeName: domain
          AttributeType: S         
      KeySchema:
        - AttributeName: appId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI_domain
          KeySchema:
            - AttributeName: domain
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
      StreamSpecification:
              StreamViewType: NEW_AND_OLD_IMAGES
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
