Resources:
  AppsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.appsTableName}
      AttributeDefinitions:
        - AttributeName: appId
          AttributeType: S      
      KeySchema:
        - AttributeName: appId
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
