Resources:
  ChatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.chatsTableName}
      AttributeDefinitions:
        - AttributeName: appEosAccount
          AttributeType: S
        - AttributeName: counterPartyAccount
          AttributeType: S
        - AttributeName: sentAt
          AttributeType: N
      KeySchema:
        - AttributeName: appEosAccount
          KeyType: HASH
        - AttributeName: counterPartyAccount
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI_appEosAccountSentAt
          KeySchema:
            - AttributeName: appEosAccount
              KeyType: HASH
            - AttributeName: sentAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
