Resources:
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.messagesTableName}
      AttributeDefinitions:
        - AttributeName: messageKey
          AttributeType: S
        - AttributeName: smsNumber
          AttributeType: S
        - AttributeName: emailAddress
          AttributeType: S
        - AttributeName: eosAccount
          AttributeType: S
        - AttributeName: appId
          AttributeType: S
        - AttributeName: sentAt
          AttributeType: N
        - AttributeName: appParticipants
          AttributeType: S
      KeySchema:
        - AttributeName: messageKey
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI_smsNumber
          KeySchema:
            - AttributeName: smsNumber
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: GSI_emailAddress
          KeySchema:
            - AttributeName: emailAddress
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: GSI_eosAccount
          KeySchema:
            - AttributeName: eosAccount
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: GSI_appId
          KeySchema:
            - AttributeName: appId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: GSI_appParticipants
          KeySchema:
            - AttributeName: appParticipants
              KeyType: HASH
            - AttributeName: sentAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
