Resources:
  OauthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.oauthTableName}
      AttributeDefinitions:
        - AttributeName: accessToken
          AttributeType: S
        - AttributeName: appId
          AttributeType: S
        - AttributeName: authorizationCode
          AttributeType: S
        - AttributeName: eosAccount
          AttributeType: S
        - AttributeName: refreshToken
          AttributeType: S
        - AttributeName: oauthTokenStatus
          AttributeType: S
        - AttributeName: appEosAccount
          AttributeType: S
      KeySchema:
        - AttributeName: authorizationCode
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI_accessToken
          KeySchema:
            - AttributeName: accessToken
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: GSI_eosAccount_appId
          KeySchema:
            - AttributeName: eosAccount
              KeyType: HASH
            - AttributeName: appId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: GSI_eosAccount_oauthTokenStatus
          KeySchema:
            - AttributeName: eosAccount
              KeyType: HASH
            - AttributeName: oauthTokenStatus
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: GSI_appEosAccount_oauthTokenStatus
          KeySchema:
            - AttributeName: appEosAccount
              KeyType: HASH
            - AttributeName: oauthTokenStatus
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: GSI_appId_oauthTokenStatus
          KeySchema:
            - AttributeName: appId
              KeyType: HASH
            - AttributeName: oauthTokenStatus
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: GSI_refreshToken
          KeySchema:
            - AttributeName: refreshToken
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
