Resources:
  ScopeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.scopeTableName}
      AttributeDefinitions:
        - AttributeName: scope
          AttributeType: S
      KeySchema:
        - AttributeName: scope
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
